/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_teamlab_selectware_learnings_JniLdaScvb0 */

#ifndef _Included_com_teamlab_selectware_learnings_JniLdaScvb0
#define _Included_com_teamlab_selectware_learnings_JniLdaScvb0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_teamlab_selectware_learnings_JniLdaScvb0
 * Method:    fit
 * Signature: ([[I[[I)V
 */
JNIEXPORT void JNICALL Java_com_teamlab_selectware_learnings_JniLdaScvb0_fit
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
